= jmzqc Parser, Writer and Validator for the HUPO-PSI MzQC format
Nils Hoffmann <nils.hoffmann@cebitec.uni-bielefeld.de>
:toc: macro

image:https://img.shields.io/badge/lifecycle-experimental-orange.svg["Lifecycle: Experimental", link="https://github.com/lifs-tools/jmqzc"] image:https://github.com/MS-Quality-hub/jmzqc/actions/workflows/ci.yml/badge.svg["CI", link="https://github.com/MS-Quality-hub/jmzqc/actions/workflows/ci.yml"] image:https://img.shields.io/maven-central/v/org.lifs-tools/jmzqc[Maven Central]
//image:https://img.shields.io/github/release/lifs-tools/jgoslin.svg["Latest Release", link="https://github.com/lifs-tools/jmzqc/releases/latest"] 
//image:https://zenodo.org/badge/DOI/10.5281/zenodo.3826474.svg["DOI", link="https://doi.org/10.5281/zenodo.3826474"]

This project is a parser, validator and serializer implementation for https://github.com/HUPO-PSI/mzQC[mzQC: Reporting and exchange format for mass spectrometry quality control data].

The Maven site with JavaDoc is available https://MS-Quality-hub.github.io/jmzqc/index.html[here].

== Related Projects

- https://github.com/HUPO-PSI/mzqc[The official HUPO-PSI mzQC project]

== Table of contents
toc::[]

== Building the project and generating client code from the command-line

In order to build the client code and run the unit tests, execute the following command from a terminal:

    ./mvnw install

This generates the necessary domain specific code for Java. 

== Using the project code releases via Maven Central

Note: The library will be made available via Maven Central. To search for releases, go to https://search.maven.org/search?q=org.lifs-tools

To use the parser libraries (reading and validation) in your own Maven projects, use the following dependency:

  <dependency>
    <groupId>org.lifs-tools</groupId>
    <artifactId>jmzqc</artifactId>
    <version>${jmzqc.version}</version>
  </dependency>

where `jmzqc.version` is the version of jmzqc you wish to use, e.g. for a release version:

  <properties>
    <jmzqc.version>1.0.0</jmzqc.version>
  </properties>

as defined in the properties section of your pom file.

== Using the API programmatically

=== Reading MzQC JSON into the object model

To parse a JSON string directly:

  MzQC mzQc = Converter.fromJsonString(....);

Alternatively, to read the content from a file:

  MzQC mzQc = Converter.fromFile(new File("path/to/file.mzQC"));

Or, to read from a URL:

  MzQC mzQc = Converter.fromUrl(new URL("https://raw.githubusercontent.com/HUPO-PSI/mzQC/main/specification_documents/draft_v1/examples/QC2-sample-example.mzQC"));
  
=== Writing an MzQC object model to JSON

You can use the jmzQC API to create an MzQC object:

  var inputFileCvParams = asList(new CvParameter("MS:1000747", null, "completion time", "2017-12-08-T15:38:57Z"));
  var infi = new InputFile(new CvParameter("MS:1000584", null, "mzML format", null), inputFileCvParams, new URI("file:///dev/null"), "file.raw");
  var anso = new AnalysisSoftware("QC:9999999", null, "bigwhopqc", null, new URI("file:///dev/null"), "1.2.3");  
  var meta = new Metadata(asList(anso), null, asList(infi), "test_metadata");
  var qm = new QualityMetric("QC:4000053", null, "RT duration", 99, null);
  var rq = new BaseQuality(meta, asList(qm));
  var sq = new BaseQuality(meta, asList(qm));
  var cv = new ControlledVocabulary("TEST", new URI("https://www.eff.off"), null);
  var mzqc = new MzQC(
          null,
          null,
          asList(cv),
          OffsetDateTime.now(),
          "pytest-test file",
          asList(rq),
          asList(sq),
          "1.0.0");

In order to write an MzQC object, you can also use the Converter:

  Converter.toJsonFile(mzqc, new File("path/to/write/file.mzQC"));

=== Validating MzQC

You can validate MzQC files local files or JSON string:
  
  Set<ValidationMessage> messages = Converter.validate(new File("path/to/file.mzQC"));

Or from a URL:

  Set<ValidationMessage> messages = Converter.validate(new URL("https://raw.githubusercontent.com/HUPO-PSI/mzQC/main/specification_documents/draft_v1/examples/QC2-sample-example.mzQC"));

Or immediately from an MzQC object:

  Set<ValidationMessage> messages = Converter.validate(mzqc));
  
The returned messages will be empty, if validation was successful. Otherwise, the messages will contain information on what was wrong and where in your mzQC document the issue was detected.

== References

//  * **https://pubs.acs.org/doi/10.1021/acs.analchem.8b04310[N. Hoffmann et al., Analytical Chemistry 2019; Jan;91(5):3302-3310.] https://pubs.acs.org/doi/pdf/10.1021/acs.analchem.8b04310[PDF File.] https://www.ncbi.nlm.nih.gov/pubmed/30688441[PubMed record].**

//* https://doi.org/10.1101/2020.04.17.046656[D. Kopczynski et al., Biorxiv, April 20th, 2020]

