= jmzqc Parser, Writer and Validator for the HUPO-PSI MzQC format
Nils Hoffmann <nils.hoffmann@cebitec.uni-bielefeld.de>
:toc: macro

image:https://img.shields.io/badge/lifecycle-experimental-orange.svg["Lifecycle: Experimental", link="https://github.com/lifs-tools/jmqzc"] image:https://github.com/MS-Quality-hub/jmzqc/actions/workflows/ci.yml/badge.svg["CI", link="https://github.com/MS-Quality-hub/jmzqc/actions/workflows/ci.yml"] image:https://img.shields.io/maven-central/v/org.lifs-tools/jmzqc[Maven Central]
//image:https://img.shields.io/github/release/lifs-tools/jgoslin.svg["Latest Release", link="https://github.com/lifs-tools/jmzqc/releases/latest"] 
//image:https://zenodo.org/badge/DOI/10.5281/zenodo.3826474.svg["DOI", link="https://doi.org/10.5281/zenodo.3826474"]

This project is a parser, validator and serializer implementation for https://github.com/HUPO-PSI/mzQC[mzQC: Reporting and exchange format for mass spectrometry quality control data].

The Maven site with JavaDoc is available https://MS-Quality-hub.github.io/jmzqc/index.html[here].

== Related Projects

- https://github.com/HUPO-PSI/mzqc[The official HUPO-PSI mzQC project]

== Table of contents
toc::[]

== Building the project and generating client code from the command-line

In order to build the client code and run the unit tests, execute the following command from a terminal:

    ./mvnw install

This generates the necessary domain specific code for Java. 

== Using the project code releases via Maven Central

Note: The library will be made available via Maven Central. To search for releases, go to https://search.maven.org/search?q=org.lifs-tools

To use the parser libraries (reading and validation) in your own Maven projects, use the following dependency:

  <dependency>
    <groupId>org.lifs-tools</groupId>
    <artifactId>jmzqc</artifactId>
    <version>${jmzqc.version}</version>
  </dependency>

where `jmzqc.version` is the version of jmzqc you wish to use, e.g. for a release version:

  <properties>
    <jmzqc.version>1.0.0</jmzqc.version>
  </properties>

as defined in the properties section of your pom file.

== Using the API programmatically

=== Reading MzQC JSON into the object model

To parse a JSON string directly:

  Coordinate c = Converter.fromJsonString(....);

Alternatively, to read the content from a file:

  Coordinate c = Converter.fromFile(new File("path/to/file.mzQC"));

Or, to read from a URL:

  Coordinate c = Converter.fromUrl(new Url("https://raw.githubusercontent.com/HUPO-PSI/mzQC/master/doc/examples/QC2-sample-example.mzQC"));
  
You can then access the MzQC object:

  MzQC mzQc = c.getMzQC();

=== Writing an MzQC object model to JSON

In order to write an MzQC object:

  Converter.toFile(mzQc, new File("path/to/write/file.mzQC"));

== References

//  * **https://pubs.acs.org/doi/10.1021/acs.analchem.8b04310[N. Hoffmann et al., Analytical Chemistry 2019; Jan;91(5):3302-3310.] https://pubs.acs.org/doi/pdf/10.1021/acs.analchem.8b04310[PDF File.] https://www.ncbi.nlm.nih.gov/pubmed/30688441[PubMed record].**

//* https://doi.org/10.1101/2020.04.17.046656[D. Kopczynski et al., Biorxiv, April 20th, 2020]

