name: CI 

# ci workflow
on: [push]

jobs:
    publish:
        name: Build the Code
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: 11
        - name: Set Git user
          run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
        - name: Build and Run Tests
          run: ./mvnw -B --update-snapshots verify
          env:
            DEFAULT_BRANCH: master
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
