name: Release

# Release workflow
on:
        #  push:
        #    branches:
        #      - release
  release:
    types: [created]

jobs:
    publish:
        name: Release the Code
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: 11
        - name: Set Git user
          run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
        - name: Publish Jar
          run: mvn -B deploy
          env:
            DEFAULT_BRANCH: master
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
